#!/bin/bash

CONTAINER_REGISTRY="kakalin"
CONTAINER_REPOSITORY="pandoc"
CONTAINER_TAG="latest"

docker build --rm -t $CONTAINER_REGISTRY/$CONTAINER_REPOSITORY:$CONTAINER_TAG .
docker push $CONTAINER_REGISTRY/$CONTAINER_REPOSITORY:$CONTAINER_TAG
